"""add model file_path 1.0

Revision ID: 4f3ef1546989
Revises: 99d90e235844
Create Date: 2026-03-07 18:21:48.958386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4f3ef1546989"
down_revision: Union[str, Sequence[str], None] = "99d90e235844"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_path",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name_figure", sa.String(length=255), nullable=True),
        sa.Column("name_file", sa.String(length=255), nullable=True),
        sa.Column("abspath", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("file_path")
    # ### end Alembic commands ###
