"""add model oval and rect

Revision ID: 687383375437
Revises: 4f3ef1546989
Create Date: 2026-03-07 21:55:15.004134

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "687383375437"
down_revision: Union[str, Sequence[str], None] = "4f3ef1546989"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ovals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("x_center", sa.Integer(), nullable=False),
        sa.Column("y_center", sa.Integer(), nullable=False),
        sa.Column("radius_x", sa.Integer(), nullable=False),
        sa.Column("radius_y", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rectangles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("x_left_up", sa.Integer(), nullable=False),
        sa.Column("y_left_up", sa.Integer(), nullable=False),
        sa.Column("x_right_down", sa.Integer(), nullable=False),
        sa.Column("y_right_down", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rectangles")
    op.drop_table("ovals")
    # ### end Alembic commands ###
