"""create models

Revision ID: bc4f67ab8f83
Revises: 3d86b5a44cdc
Create Date: 2026-03-06 15:01:09.831032

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc4f67ab8f83"
down_revision: Union[str, Sequence[str], None] = "3d86b5a44cdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Integer(), nullable=False),
        sa.Column("y", sa.Integer(), nullable=False),
        sa.Column("radius", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("x_left", sa.Integer(), nullable=False),
        sa.Column("y_left", sa.Integer(), nullable=False),
        sa.Column("x_right", sa.Integer(), nullable=False),
        sa.Column("y_right", sa.Integer(), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "squares",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("x_left_up", sa.Integer(), nullable=False),
        sa.Column("y_left_up", sa.Integer(), nullable=False),
        sa.Column("x_left_down", sa.Integer(), nullable=False),
        sa.Column("y_left_down", sa.Integer(), nullable=False),
        sa.Column("side", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("squares")
    op.drop_table("lines")
    op.drop_table("circles")
    # ### end Alembic commands ###
