"""update model oval

Revision ID: c30c26ccd1b6
Revises: 687383375437
Create Date: 2026-03-07 22:37:46.477946

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c30c26ccd1b6"
down_revision: Union[str, Sequence[str], None] = "687383375437"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ovals", sa.Column("x_radius", sa.Integer(), nullable=False))
    op.add_column("ovals", sa.Column("y_radius", sa.Integer(), nullable=False))
    op.drop_column("ovals", "radius_y")
    op.drop_column("ovals", "radius_x")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ovals", sa.Column("radius_x", sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column("ovals", sa.Column("radius_y", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("ovals", "y_radius")
    op.drop_column("ovals", "x_radius")
    # ### end Alembic commands ###
